plugins: 
  - jest
env:
  node: true
extends: 
  - 'airbnb-base' 
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  linebreak-style: 0
  consistent-return: 0
  no-unused-vars: 0
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] 
  
